import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Jakob&apos;s Ultimatives Buzzer Game</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
        <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
          <span className="text-[hsl(280,100%,70%)]">Jakob&apos;s</span>{" "}
          Ultimatives Buzzer Game
        </h1>
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
          <Link
            className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
            href="https://create.t3.gg/en/usage/first-steps"
            target="_blank"
          >
            <h3 className="text-2xl font-bold">Player →</h3>
            <div className="text-lg">
              Hier musst du drücken, wenn du
              <span className="underline"> nicht</span> Jakob bist!
            </div>
          </Link>
          <div className="form-control w-full max-w-xs">
            <label className="label">
              <span className="label-text">What is your name?</span>
            </label>
          </div>
          <Link
            className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
            href={"/jakob"}
          >
            <h3 className="text-2xl font-bold">Jakob →</h3>
            <div className="text-lg">
              Hier musst du drücken, wenn du Jakob bist!
            </div>
          </Link>
          <div className="form-control w-full max-w-xs">
            <label className="label">
              <span className="label-text">
                Jakob&apos;s super geheimer SecretKey
              </span>
            </label>
          </div>
        </div>
        <p className="text-2xl text-white">
        </p>
      </div>
    </>
  );
};

export default Home;
