import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";

export const metadata = {
    title: "Mumbai Buzzer v2",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body className="min-h-screen bg-gradient-to-br from-[#2e026d] to-[#15162c]">
                    {children}
                </body>
            </html>
        </ClerkProvider>
    );
}
